# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='auth_user',
        ),
    ]
